// Library
import express, { request, response } from "express";
import bcrypt from "bcryptjs";
import  jwt  from "jsonwebtoken";
import passport from "passport";

// Models
import { UserModel } from "../../database/user";

const Router = express.Router();

/* 
Route: /signup
Desc: signup with email and password
params: none
access:public
method:post
*/

Router.post("/signup", async (request, response) => {
    try {
        const { email, phoneNumber} = request.body.credentials;
        // check whether email exists
        await UserModel.findByEmailAndPhone(email, phoneNumber);
        

        // save to DB
        const newUser = await UserModel.create(request.body.credentials)

        
        // generate JWT auth token
        const token = newUser.generateJwtToken();
        // here the ZomatoAPP is the token generated by the jwt
        // return
        return response.status(200).json({token, status: "success"})
        
    } catch (error) {
        return response.status(500).json({ error : error.message });
    }
});

/*
Route     /signin
Des       Signin with email and password
Params    none
Access    Public
Method    POST  
*/
Router.post("/signin", async (request, response) => {
    try {
    const { email, phoneNumber} = request.body.credentials;  
      // await ValidateSignin(request.body.credentials);
  
      const user = await UserModel.findByEmailAndPassword(request.body.credentials);
  
      const token = user.generateJwtToken();
      return response.status(200).json({ token, status: "success" });
    } catch (error) {
      return response.status(500).json({ error: error.message });
    }
});

/*
Route     /google
Des       Google Signin
Params    none
Access    Public
Method    GET  
*/
Router.get(
  "/google",
  passport.authenticate("google", {
    scope: [
      "https://www.googleapis.com/auth/userinfo.profile",
      "https://www.googleapis.com/auth/userinfo.email",
    ],
  })
);

/*
Route     /google/callback
Des       Google Signin Callback
Params    none
Access    Public
Method    GET  
*/
Router.get(
  "/google/callback",
  passport.authenticate("google", { failureRedirect: "/" }),
  (req, res) => {
    return res.redirect(
      `http://localhost:3000/google/${req.session.passport.user.token}`
    );
  }
);



  

export default Router;